### PR TITLE
change gen emulate frequency

### PR DESCRIPTION
**Pull request by CAJan93**

### CODE REVIEW

**Comment by neverchanje** [comment]
Hi, Jan, You can increase the device number if you want higher throughput. Is increasing frequency to 1s a must?

**Comment by skyzh** [comment]
> Is increasing frequency to 1s a must?

Otherwise a user will observe updates in MV every 10secs, which is not good for a live demo. Also the SQL query also doesn't look well-constructed for live demos. It's hard to observe any update, and we removed the filter to make the data "updating in real-time".

**Comment by skyzh** [comment]
But I would say it's not a must for this repo. Probably we will just keep this change for live demos and don't get it into the main branch. 🤪

**Comment by neverchanje** [comment]
Not a problem. This demo is primarily used for demo. It's not for benchmarking purposes.

**Comment by CAJan93** [comment]
Sorry @skyzh did not know that. Should we undo the change?

**Comment by skyzh** [comment]
No problem, I think it's fine.

**Pull request merged**
